//analog input pins
#define ARDUPIN_ANALOG_MIC_L 0
#define ARDUPIN_ANALOG_MIC_C 1
#define ARDUPIN_ANALOG_MIC_R 2
#define ARDUPIN_ANALOG_CURRENT 3
#define ARDUPIN_ANALOG_VOLTAGE 4
#define ARDUPIN_ANALOG_IR 5
