// PINS on ARDUINO
#define ARDUPIN_SERIAL_USB_RX 1
#define ARDUPIN_SERIAL_USB_TX 0
#define ARDUPIN_LEDMUX_DATA 24
#define ARDUPIN_LEDMUX_CLK 23
#define ARDUPIN_LEDMUX_SEL 22
#define ARDUPIN_PWM_NOSE_R 9
#define ARDUPIN_PWM_NOSE_G 8
#define ARDUPIN_PWM_NOSE_B 11
//FIXME check those pins if connectable
#define ARDUPIN_AMP_SHUT 38
#define ARDUPIN_AMP_MUTE 39
#define ARDUPIN_SERIAL_TTS_RX 17
#define ARDUPIN_SERIAL_TTS_TX 16
#define ARDUPIN_I2C_SDA 20
#define ARDUPIN_I2C_SCL 21
#define ARDUPIN_HEARTBEAT_LED 13
